using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace InterceptorSourceGenerator;

[Generator]
public class InterceptorSourceGenerator : IIncrementalGenerator {
  public void Initialize(IncrementalGeneratorInitializationContext context) {
    // Step 1: Find all Console.WriteLine invocations in the target code.
    // This uses the same pattern-matching approach as the original C# 12
    // version of this generator.
    var provider = context.SyntaxProvider
      .CreateSyntaxProvider(
        (s, _) => s is InvocationExpressionSyntax {
          Expression: MemberAccessExpressionSyntax {
            Name.Identifier.Text: "WriteLine",
            Expression: IdentifierNameSyntax {
              Identifier.Text: "Console"
            }
          }
        },
        // Step 2: For each matching call, use the NEW Roslyn API to get
        // the interceptable location. This replaces the old approach of
        // manually extracting file path, line, and column numbers.
        (ctx, ct) => {
          var location = ctx.SemanticModel.GetInterceptableLocation(
            (InvocationExpressionSyntax)ctx.Node, ct);
          if (location is null) return ((int Version, string Data, string Display)?)null;
          // Extract the data we need into a simple value tuple, so the
          // incremental generator can cache results properly without
          // holding references to Roslyn compilation objects.
          return (location.Version, location.Data, location.GetDisplayLocation());
        })
      .Where(info => info.HasValue)
      .Select((info, _) => info!.Value);

    context.RegisterSourceOutput(provider.Collect(), GenerateCode);
  }

  private void GenerateCode(SourceProductionContext ctx,
    ImmutableArray<(int Version, string Data, string Display)> locations) {
    if (locations.IsEmpty) return;

    // Build the InterceptsLocation attributes for each call site.
    // Each attribute uses the new (int version, string data) signature
    // instead of the old (string filePath, int line, int column) form.
    var attributeLines = string.Join("\n    ",
      locations.Select(l =>
        $"[InterceptsLocation({l.Version}, \"{l.Data}\")]"));

    // Include human-readable locations as comments, using
    // GetDisplayLocation() for clarity.
    var displayComments = string.Join("\n    // ",
      locations.Select(l => l.Display));

    var code = $$"""
                 // <auto-generated/>
                 // This file was generated by InterceptorSourceGenerator.
                 //
                 // Intercepted Console.WriteLine calls at:
                 //   {{displayComments}}

                 #nullable enable
                 #pragma warning disable CS9113 // Primary constructor parameters are read by the compiler

                 using System;

                 namespace System.Runtime.CompilerServices {
                   // The attribute must be defined by the generator. The new signature
                   // uses (int version, string data) instead of the old
                   // (string filePath, int line, int column) form.
                   // The `data` parameter is an opaque base64-encoded blob containing
                   // an xxHash128 checksum of the source file, the character position,
                   // and the display filename.
                   [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                   file sealed class InterceptsLocationAttribute(int version, string data) : Attribute
                   {}
                 }

                 namespace InterceptorSourceGenerator {
                   using System.Runtime.CompilerServices;
                   file static class Interceptors {
                     {{attributeLines}}
                     internal static void InterceptorMethod(string? output) {
                       Console.WriteLine($"Intercepted! (Original output: {output})");
                     }
                   }
                 }
                 """;
    ctx.AddSource("WriteLineInterceptor.g.cs", SourceText.From(code, Encoding.UTF8));
  }
}